version: "3"

services:
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    networks:
      local:
        ipv4_address: 10.10.0.8

networks:
  local:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/24