version: "3.9"

services:
  mongo:
    container_name: mongo-student
    image: mongo:latest
    restart: always
    environment:
      MONDODB_DATABASE: student-management
      MONGO_INITDB_DATABASE: student-management
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
